### ISSUE TITLE
From another namespace webhook is not triggering 

### ISSUE THREAD

**Issue by shaikshakeel** [danfromtitan/envars-from-node-labels#1]
Hi, 

When I am trying to run my pods in another namespace. web hook is not triggering. I changed `namespaceSelector` to proper namespace and enabled containers also.  still it is not working. I don't see any logs in webhook pod also. 

Am I missing anything.? 

And FYI We are using `kustomize`

**Comment by danfromtitan** [comment]
Make sure the webhook pod's running and there is a log line indicating the service has started:

```
2022/03/11 23:07:03 starting admission controller ...
```

As for kustomize, you'd have to provide your own installation method for that.

**Comment by shaikshakeel** [comment]
Hi @danfromtitan  Yes. I can see above log line in webbhook. for given examples it is working fine. If I remove `namespaceSelector` it is working fine, from every namespace webhook is receiving events. but if I add `namespaceSelector` for a specific namespace it is not working.

**Comment by danfromtitan** [comment]
The examples are also using a namespace different than default, any other namespace should work as long as resources are PODs created in that namespace. Double-check the mutatingwebhookconfigurations you have created has the right name under namespaceSelector.
