### ISSUE TITLE
Helm Chart: Multiple namespaces in selector

### ISSUE THREAD

**Issue by mateuszdrab** [danfromtitan/envars-from-node-labels#16]
Hey buddy

Thanks for creating the chart for this, I'm just about to move to it but I noticed that the chart only allows one namespace to be selected as per:
```
    namespaceSelector:
      matchLabels:
        name: {{ .Values.webhook.namespaceSelector }}
```

Any chance to get this adjusted to perhaps allow multiple namespaces or a custom label name?

Thanks

**Comment by danfromtitan** [comment]
Yes, I'll add that.

**Comment by mateuszdrab** [comment]
> Yes, I'll add that.

Thanks, let me know once it's added 😊

**Comment by danfromtitan** [comment]
@mateuszdrab - someone else go to fix this before I had a chance to look at it.
Please let me know whether [this PR](#19) solves the issue (make sure to pull the latest from the master branch to pick the helm chart version bump)
