### ISSUE TITLE
Service went into `CrashLoopBackOff` failing to create a secret

### ISSUE THREAD

**Issue by ivankovnatsky** [danfromtitan/envars-from-node-labels#4]
Something weird started to happen, when had just a common helm deploys, the envars started to log this:

```
2022/05/13 12:29:20 error creating secret envars-95237cb9-5396-499a-bd0a-dfb2d7660c62 in namespace black: secrets "envars-95237cb9-5396-499a-bd0a-dfb2d7660c62" already exists
```

Pods got stuck in Terminated/Pending, also can't seem to delete pods in Terminating/Pending state since it wants to communicate with the envars-webook:

```
Delete failed with Internal error occurred: failed calling webhook "envars-webhook.webhook.svc": Post "https://envars-webhook.webhook.svc:443/mutate?timeout=30s": no
```

```
│   Warning  FailedScheduling  44s (x12 over 18m)  default-scheduler  binding rejected: running Bind plugin "DefaultBinder": Internal error occurred: failed calling web │
│ hook "envars-webhook.webhook.svc": Post "https://envars-webhook.webhook.svc:443/mutate?timeout=30s": no endpoints available for service "envars-webhook"   
```

Our install looks like this:

```terraform
resource "null_resource" "envars_from_node_labels_tls" {
  count = var.cell_type == "bluestack" ? 1 : 0

  triggers = {
    cluster_instance_ids = filemd5("./scripts/tls.sh")
  }

  provisioner "local-exec" {
    command = "./scripts/tls.sh"
  }

  depends_on = [
    module.eks,
  ]
}

resource "null_resource" "envars_from_node_labels_deployment" {
  count = var.cell_type == "bluestack" ? 1 : 0

  triggers = {
    cluster_instance_ids = filemd5("./manifests/admission-webhook.yaml")
  }

  provisioner "local-exec" {
    command = <<-EOT
export CA_PEM_B64="$(kubectl get secret -n webhook envars-webhook-tls -o 'go-template={{index .data "ca.crt"}}')"
j2 ./manifests/admission-webhook.yaml | kubectl apply -f -
kubectl rollout restart -n webhook deployment envars-webhook || true
EOT
  }

  depends_on = [
    null_resource.envars_from_node_labels_tls,
    module.eks,
  ]
}
```

Do you know any possible clues for that errors?

**Comment by danfromtitan** [comment]
Let's start troubleshooting from the last error: no endpoints available for service "envars-webhook". Can you confirm there is an endpoint for the service: 

```
kubectl get ep -n webhook
``` 

Typically deployment errors happen when the webhook POD is gone, but you're saying you can retrieve logs from it, so I assume the webhook POD and service are still there.

**Comment by danfromtitan** [comment]
The first error is probably because Helm tries to rollback and it restores the POD from its previous manifest, the one that has the _envars-secret-name_ label. When the restored POD goes in the binding phase, the webhook tries to create a secret that already exists.

Now, the secret should have been deleted when the POD was terminated, but that didn't happen as you saw in your second log.

Deployments can run into a chicken & egg problem when the webhook availability is affected.

**Comment by ivankovnatsky** [comment]
Hm, deleted `envars-` secrets and deleted `envars-webhook` pods, seem working fine now.

**Comment by ivankovnatsky** [comment]
> Let's start troubleshooting from the last error: no endpoints available for service "envars-webhook". Can you confirm there is an endpoint for the service:
> 
> ```
> kubectl get ep -n webhook
> ```
> 
> Typically deployment errors happen when the webhook POD is gone, but you're saying you can retrieve logs from it, so I assume the webhook POD and service are still there.

Yes, it was there:

```
❯ kubectl get ep -n webhook
NAME             ENDPOINTS         AGE
envars-webhook   10.0.40.51:8443   28d
```

**Comment by ivankovnatsky** [comment]
> The first error is probably because Helm tries to rollback and it restores the POD from its previous manifest, the one that has the _envars-secret-name_ label. When the restored POD goes in the binding phase, the webhook tries to create a secret that already exists.
> 
> Now, the secret should have been deleted when the POD was terminated, but that didn't happen as you saw in your second log.
> 
> Deployments can run into a chicken & egg problem when the webhook availability is affected.

Thanks, yeah, that was probably it. Funny thing we did pass same code to staging and it went fine. While on development I had noticed this weird thing. That is not of webhook concern error, with the helm deployment rather. Will close this, thanks for the fast reply!

**Comment by danfromtitan** [comment]
I was pondering whether I should ignore the envars- secret already exists error and re-use the secret, but in this case the restored POD could end-up on another node, thus you'd now have wrong NODE_ values in the container.

**Comment by ivankovnatsky** [comment]
> thus you'd now have wrong NODE_ values in the container.

yes, exactly. that is tricky, and the current behavior is pretty proactive in this regard.
